# site settings
title: Ana Aldeguer Fernández
subtitle: Portfolio
email: anaaldfer@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: ""
url: https://anaaldeguerfernandez.github.io
author: Ana Aldeguer Fernández
city: Alicante
state: Europe
country: Spain
phone: (+34) 655 392 654

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  LinkedIn: https://es.linkedin.com/in/ana-aldeguer-fern%C3%A1ndez-b5a41b18a
  Behance: https://www.behance.net/AnaAldFer8fe2

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
